  name: gnome-shortcut-manager
  version: '1.1.1'
  summary: Tiny menu editor for GNOME3.
  description: |
    Tiny menu editor for GNOME3. Easily add or remove shortcuts from your dash.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    filesets:
       binaries:
        - bin/*
        - usr/bin/*
       headers:
        - “include/*.h”
  
